cfc_app/urls.py
from django.urls import URLPattern, path

from . import views

app_name = 'draft'
urlpatterns = [
    path('', views.index, name='home'),
    path('select/<int:id>/', views.select, name='select'),
    path('create-draft/', views.create_draft),
    path('reset-teams-picks/', views.reset_teams_picks),
    path('reset-draft-order/', views.reset_draft_order),
    path('reset-draft/', views.reset_draft),
    path('undo-last-pick/', views.undo_last_pick),
    path('rules/', views.rules, name='rules'),
    path('draft-end-test/', views.draft_end_test),
    path('roster/', views.roster, name='roster'),
]

cfc_config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cfc_app.urls')),
    path('players/', include('players.urls')),
]

players/urls.py
from django.urls import path

from . import views

app_name = 'players'
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup'),
]

cfc_app/models.py
from django.db import models
from players.models import User
import random

class Conference(models.Model):
    name = models.CharField(max_length=50)
    abbreviation = models.CharField(max_length=12, null=True)

    def __str__(self):
        return f'{self.abbreviation} - {self.name}'

class Division(models.Model):
    name = models.CharField(max_length=20)
    conference = models.ForeignKey(Conference, on_delete=models.PROTECT, related_name='divisions')

    def __str__(self):
        return f'{self.name} - {self.conference}'

class FbsTeam(models.Model):
    # list of teams for the challenge
    school_name = models.CharField(max_length=50)
    school_abbrev = models.CharField(max_length=10, null=True, blank=True)
    nickname = models.CharField(max_length=50)
    conference_name = models.ForeignKey(Conference, on_delete=models.PROTECT, null=True, related_name='teams')
    division_name = models.ForeignKey(Division, on_delete=models.PROTECT, null= True, blank=True, related_name='teams')
    conference_abbrev = models.CharField(max_length=12)
    owned = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    ap_preseason_ranking = models.IntegerField(null=True, blank=True)
    fpi_ranking = models.IntegerField(null=True, blank=True)
    cbs_ranking = models.IntegerField(null=True, blank=True)
    

    def __str__(self):
        return f'{self.school_name} - {self.owned}' if self.owned != None else f'{self.school_name}'
        
class League(models.Model):
    name = models.CharField(max_length=25, blank=True, null=True)
    player = models.ManyToManyField(User, blank=True)
    
    def __str__(self):
        return self.name

class Pick(models.Model):
    player = models.ForeignKey(User, on_delete=models.PROTECT, related_name='picks')
    pick_number = models.IntegerField(null=True, blank=True)
    team = models.OneToOneField(FbsTeam, on_delete=models.PROTECT, null=True, blank=True)
    draft = models.ForeignKey('Draft', on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return f'pick {self.pick_number} - {self.player.username} -> {self.team.school_name}' if self.team != None else f'pick {self.pick_number} - {self.player.username}'

class Draft(models.Model):
    players = models.ManyToManyField(User, blank=True)
    current_pick = models.IntegerField(default=1)
    live = models.BooleanField(default=False)

    def create_draft_order(self): # need 7 players for draft to work
        from random import shuffle
        # print(self.players.all())
        players = list(self.players.all())
        # print(players)
        shuffle(players)
        # print(players)
        # print(players[0].username, players[0].draft_order)
        k = 1
        for player in players:
            player.draft_order = k
            player.save()
            print(player.username, player.draft_order)
            k += 1
        # give random numbers 1-7 for draft position to each player
        range_picks = (len(players) * 8) + 1
        # print(range_picks)
        player_draft_position = 1
        counting = 'up'
        for pick in range(1, range_picks):
            # print(f'{players[player_draft_position - 1]} has pick {pick}')
            Pick.objects.create(
                player = players[player_draft_position - 1],
                pick_number = pick,
                draft = self
            )
            player.save()
            if counting == 'up':
                if player_draft_position == 7:
                    counting = 'down'
                else:
                    player_draft_position += 1
            elif counting == 'down':
                if player_draft_position == 1:
                    counting = 'up'
                else:
                    player_draft_position -= 1
        return
        

cfc_app/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, JsonResponse

from .models import Conference, Division, FbsTeam, Draft, Pick
from players.models import User
from django.contrib.auth.decorators import user_passes_test


def index(request):
    teams = FbsTeam.objects.all()
    conferences = Conference.objects.all()
    divisions = Division.objects.all()
    message = request.GET.get('message')
    draft = Draft.objects.first()
    players = draft.players.order_by('draft_order')
    current_pick = draft.current_pick
    pick = None
    if current_pick < 57 and draft.live:
        pick = Pick.objects.get(pick_number=draft.current_pick)
        users_turn = pick.player == request.user
    else:
        users_turn = False

    context = {
        'teams' : teams,
        'conferences' : conferences,
        'divisions' : divisions,
        'message' : message,
        'players' : players,
        'draft' : draft,
        'users_turn' : users_turn,
        'current_pick' : current_pick,
        'pick' : pick,
    }

    print(request.GET.get('message'))

    return render(request, 'cfc_app/index.html', context)

def select(request,id):
    selected_team = FbsTeam.objects.get(id=id)
    draft = Draft.objects.first()
    pick = Pick.objects.get(pick_number=draft.current_pick)
    teams_owned = FbsTeam.objects.filter(owned__isnull=False).count()

    if teams_owned == 56:
        return redirect('draft:home')
    else:
        if request.user.is_superuser or request.user == pick.player:
            # if pick.player != request.user:
            #     return redirect('/?message=Its+not+your+turn')

            selected_team.owned = pick.player
            # request.user
            selected_team.save()
            pick.team = selected_team
            pick.save()
            draft.current_pick += 1
            draft.save()
            print(selected_team)
            return redirect('draft:home')
        else:
            return redirect('/?message=Its not your turn')

# def drop_team(request,id):
#     dropped_team = FbsTeam.objects.get(id=id)


@user_passes_test(lambda u: u.is_superuser)
def create_draft(request):
    draft = Draft.objects.first()
    players = list(draft.players.all())
    if len(players) == 7:
        draft.live = True
        draft.save()
        draft.create_draft_order()
        return redirect('draft:home')
    else:
        return redirect('/?message=DRAFT+MUST+HAVE+7+PLAYERS')


@user_passes_test(lambda u: u.is_superuser, '/?message=resetting teams denied')
def reset_teams_picks(request):
    FbsTeam.objects.update(owned=None)
    Pick.objects.update(team=None)
    return HttpResponse('reset all teams to not owned - reset all picks to None')

@user_passes_test(lambda u: u.is_superuser, '/?message=YOU+cant+reset+the+draft+order')
def reset_draft_order(request):
    User.objects.update(draft_order=None)
    Draft.objects.update(current_pick=1)
    Pick.objects.all().delete()
    return redirect('draft:home')

@user_passes_test(lambda u: u.is_superuser, '/?message=YOU+cant+reset+the+draft+order')
def reset_draft(request):
    FbsTeam.objects.update(owned=None)
    Pick.objects.update(team=None)
    User.objects.update(draft_order=None)
    Draft.objects.update(current_pick=1, live=False)
    Pick.objects.all().delete()
    draft = Draft.objects.first()
    draft.live = True
    draft.save()
    draft.create_draft_order()
    
    return redirect('draft:home')

@user_passes_test(lambda u: u.is_superuser, '/?message=YOU+cant+reset+the+draft+order')
def undo_last_pick(request):
    draft = Draft.objects.first()
    draft.current_pick -= 1
    draft.save()
    pick = Pick.objects.get(pick_number=draft.current_pick)
    team = pick.team
    team.owned = None
    team.save()
    pick.team = None
    pick.save()
    return redirect('draft:home')

def rules(request):
    return render (request, 'cfc_app/rules.html')

@user_passes_test(lambda u: u.is_superuser, '/?message=YOU+cant+reset+the+draft+order')
def draft_end_test(request):
    teams_owned = FbsTeam.objects.filter(owned__isnull=False).count()
    print(teams_owned)
    return HttpResponse('testing number of owned teams')

def roster(request):
    teams = FbsTeam.objects.all()
    conferences = Conference.objects.all()
    divisions = Division.objects.all()
    draft = Draft.objects.first()
    players = draft.players.order_by('draft_order')
    print(players)


    context = {
        'teams' : teams,
        'players' : players,
        'conferences' : conferences,
        'divisions' : divisions,
    }

    return render (request, 'cfc_app/roster.html', context)

def draft_pick_check(request):
    pick = Draft.objects.first().current_pick
    return JsonResponse(data={'pick': pick})

cfc_app/templates/cfc_app/roster.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Roster || CFC</title>
    <script src="https://cdn.tailwindcss.com/"></script>

</head>

<header class="fixed w-full font-medium bg-green-400 py-3 px-10 flex justify-between items-center">
    <h3 class="text-lg font-medium">College Football Challenge || ROSTER
        <a href="{% url 'draft:home' %}" class="text-base font-medium pl-48">Draft</a>
        <a href="{% url 'draft:rules' %}" class="text-base font-medium pl-8">Rules</a>
        <a href="" class="text-base font-medium pl-8">Big Board</a>
    </h3>
        <div>
            {% if request.user.is_authenticated %}
            <Span>Welcome, {{ user.username }}</Span>
            <a href="{% url 'players:logout' %}" class="
            px-2 py-1 border-black border-2 rounded-md
            hover:bg-white-800 hover:text-zinc ml-1 text-xs font-medium bg-green-400/50">Log Out</a>
            {% else %}
            <a href="{% url 'players:signup' %}" class="
            px-2 py-1 border-black border-2 rounded-md
            hover:bg-white-800 hover:text-zinc ml-1 text-xs font-mediumn bg-green-400/50">Sign Up</a>
            <a href="{% url 'players:login' %}" class="
            px-2 py-1 border-black border-2 rounded-md
            hover:bg-white-800 hover:text-zinc ml-1 text-xs font-medium bg-green-400/50">Log In</a>
            {% endif %}
            <a href="{% url 'draft:home' %}" class="
                        px-2 py-1 border-black border-2 rounded-md
                        hover:bg-white-800 hover:text-zinc ml-1 text-xs font-medium bg-green-400/50">Home</a>
        </div>    
</header>

<body>
    <div class="py-20">
        <h1 class="text-center">Current Roster where you can add/drop teams maybe trade</h1>
    </div>

    <div class="pt-4 pl-16 pr-16 pb-10">
        <table class="min-w-full divide-y divide-gray-600 border border-gray-800">
            <thead class="bg-gray-50">
                <tr class="divide-x divide-gray-500">
                    <th scope="col" class="py-2 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
                    <th scope="col" class="px-3 py-2 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-2 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-2 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-2 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-2 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-2 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-2 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-2 text-left text-sm font-semibold text-gray-900"></th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-400 bg-white">
                {% for team in teams %}
                    {% if team.owned %}
                    <tr class="divide-x divide-gray-600">
                        <td class="whitespace-nowrap py-1 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 bg-amber-400">{{team.owned.username}}</td>
                    {% endif %}
                    </tr>
                {% endfor %}

            </tbody>

    </div>

    
    
</body>

</html>